name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:      

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2️⃣ Generazione dello Snake
      - name: Generate Snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: GiuseppeLiGioi
          outputs: |
            dist/github-contribution-grid-snake.svg


